services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
  web:
    build:
      context: .
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}

  todolist:
    build:
      context: .
    container_name: todolist_container
    depends_on:
      - mysql
    ports:
      - "8000:8000"
    environment:
      DATABASE_HOST: mysql
      DATABASE_NAME: app_db
      DATABASE_USER: app_user
      DATABASE_PASSWORD: 1234

volumes:
  mysql_data:
